name: Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
      context:
        required: false
        type: string
        default: '.'
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'


jobs:
  build:
    name: Build Image

    runs-on:
      - self-hosted
      - dind-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_name }}
          tags: |
            type=match,pattern=${{ inputs.app_name }}-(v.*),group=1,event=tag
            type=ref,suffix=-{{sha}}-{{date 'X'}},event=branch

      - name: Adding tags to summary
        run: |
          echo '## Image tags' >> $GITHUB_STEP_SUMMARY
          echo '> ${{ steps.meta.outputs.tags }}' >> $GITHUB_STEP_SUMMARY

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          build-args: |
            BCV_NPM_TOKEN=${{ secrets.BCV_NPM_TOKEN }}
            APP=${{ inputs.app_name }}
