name: Build hlf-explorer

on:
  workflow_dispatch:
  push:
    tags:
      - hlf-explorer*
    branches:
      - main
      - dev
    # paths:
    #   - 'Dockerfile'
    #   - '!**.md'
    #   - '.github/workflows/build-explorer.yml'
    #   - 'app/persistence/fabric/postgreSQL/db/**'

jobs:
  build:
    uses: bcvouch/gha-workflows/.github/workflows/build-mono.yaml@main
    secrets: inherit
    with:
      image_name: bcvouch/hlf-explorer
      app_name: hlf-explorer
      dockerfile: Dockerfile
