name: Build hlf-explorer-db

on:
  workflow_dispatch:
  push:
    tags:
      - hlf-explorer-db*
    branches:
      - main
      - dev
    paths:
      - 'postgres-Dockerfile'
      - '!**.md'
      - '.github/workflows/build-explorer-db.yml'

jobs:
  build:
    uses: ./.github/workflows/build-docker.yaml
    with:
      image_name: bcvouch/hlf-explorer-db
      app_name: hlf-explorer-db
      dockerfile: postgres-Dockerfile
