name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on:
      - self-hosted
      - generic-arm
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.BCV_GITHUB_TOKEN }}
