name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on:
      - self-hosted
      - generic-arm
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.BCV_GITHUB_TOKEN }}
