name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'devspace.yaml'
      - '.release-please-manifest.json'
      - 'release-please-config.json'

jobs:
  test-npm-unit:
    uses: bcvouch/gha-workflows/.github/workflows/test-npm-unit.yaml@main
    secrets: inherit
    with:
      node_version: 20.9.0